[package]
name = "hash"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = { version = "0.8.4", default-features = false }
cipher = { version = "0.4.4", default-features = false }
zeroize = { version = "1.8.1", default-features = false }

[dev-dependencies]
hex-literal = "1.0.0"
