[target.x86_64-unknown-linux-gnu]
rustflags = [ "-Dwarnings" ]

[target.i686-unknown-linux-gnu]
rustflags = [ "-Dwarnings" ]

[target.aarch64-unknown-linux-gnu]
rustflags = [ "-Dwarnings" ]

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = [ "-Dwarnings", "-Ctarget-feature=+crt-static" ]

[target.i686-unknown-linux-musl]
linker = "musl-gcc"
rustflags = [ "-Dwarnings", "-Ctarget-feature=+crt-static" ]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = [ "-Dwarnings", "-Ctarget-feature=+crt-static" ]

[target.x86_64-pc-windows-msvc]
rustflags = [ "-Dwarnings", "-Ctarget-feature=+crt-static" ]

[target.i686-pc-windows-msvc]
rustflags = [ "-Dwarnings", "-Ctarget-feature=+crt-static" ]

[target.aarch64-pc-windows-msvc]
rustflags = [ "-Dwarnings", "-Ctarget-feature=+crt-static" ]

[target.x86_64-apple-darwin]
rustflags = [ "-Dwarnings" ]

[target.aarch64-apple-darwin]
rustflags = [ "-Dwarnings" ]
